version: "3.9"

services:
  bot:
    build:
      context: ./Discord_Bot
    container_name: discord_bot
    env_file:
      - .env
    volumes:
      - ./Discord_Bot:/app
    working_dir: /app
    command: node .
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.4.18
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  scraper:
    build:
      context: .
    container_name: selenium_scraper
    depends_on:
      - mongodb
    env_file:
      - .env

volumes:
  mongodb_data:
